[Directories]
audio_directory = "Audio/"
filtered_directory = "Filtered_Audio/"
write_directory = "Audio_Cut/"

[Main]
# Moving Average
time_short = 50 # ms
time_long = 250 # ms

# Mask Parameters
min_time = 40 # ms
threshold_overlap = 30
threshold_time = 0.4

# Denoising
noise_threshold = 8000 # Typically set above your maximum level

# Power Spectrum
target_frequency = 4000 # Hz
power_threshold = 100 # dB

# Extension (in time)
time_extension = 100 # ms