[Directories]
self = "config.toml"
#audio_path = "Audio/5hr.flac"
audio_path = "Audio/finch_full.flac"
#audio_path = "Audio/30Label.wav"
filtered_audio_directory = "Audio_Filtered/"
filtered_audio_path = "D:\\Dorian\\syllable_detection\\Audio_Filtered\\finch_full_filtered_0.flac"
#filtered_audio_path = "D:\\Dorian\\syllable_detection\\Audio_Filtered\\2hr_filtered.flac"
#filtered_audio_path = "D:\\Dorian\\syllable_detection\\Audio_Filtered\\5hr_filtered.flac"

write_directory = "Audio_Cut/"
max_length = 5

[Main]
time_short = 50
time_long = 250
fs = 30000
min_time = 40
threshold_overlap = 30
threshold_minimum_time = 40
threshold_time = 400
threshold_noise = 8000
threshold_power = 100
target_frequency = 4000
time_extension = 100
